### PR TITLE
Code cleaning and fix label of plots.

### PR DESCRIPTION
**Pull request by geonmo**
1. Add scripts "MakePlot.py" 
   - Include "usage".
2. Add function to calculate efficiency plots.
   - TProfile and TH1 can not provide Asymmetry error. So, this function return "large error".
   - I will input this function to MakePlot.py
3. Fix label "station2"->"station2_short" and "station3"->"station2_long"

### CODE REVIEW

**Comment by dildick** [comment]
@geonmo is this branch derived from latests SLHC IB?

**Comment by jshlee** [comment]
doesn't look like it. or else it would have millions of updates

**Comment by dildick** [comment]
@geonmo,  in order to merge it with official cmssw, you will need to start from a recent build. We never merge gem-sw into cms-sw straight away. gem-sw is our messy playground, too messy for cms

**Comment by jshlee** [comment]
as long it works properly with the latest IB, it should be fine.

**Comment by geonmo** [comment]
Hello, sven.
It was derived from SLHC12. 
This branch did not have gem-sw commits. So, it will not mix commits between gem-sw and official.
I checked PR to official cmssw. It can be merged with just 6 commits.(Because it is backward branch.)
If you confirm this PR, I will close without merge and PR to official cmssw.

**Pull request closed without merging**
