### PR TITLE
Merging updated code with mods by Jongseok and Giovanni - 20/04/2018

### PR DESCRIPTION
**Pull request by giovanni-mocellin**
Geometry back to A, Coordinates with vertical Z, Asymmetry problem solved, Seeding chambers not inserted by hand, Code cleaned but missing some histograms we will need as output

### CODE REVIEW

**Comment by jshlee** [comment]
can u fix the conflicts

**Comment by jshlee** [comment]
gemcrValidation is a bit of a mess right now.
you guys need to factorise a lot.
also, you need to make it so that it can run on data only.

**Comment by giovanni-mocellin** [comment]
I'm trying to resolve the conflicts, but it is getting hard... It is not possible for me to resolve them on this web page and no other ways are working now...
Do you have more privileges for doing it?
I agree the code is messy, but with this pr we tried to clean it up a little bit. We can start from this to factorize it.

**Comment by jshlee** [comment]
you can just merge the original copy and fix conflicts and push again

**Pull request merged**
