### PR TITLE
update from cms-sw/CMSSW_6_2_X_SLHC

### PR DESCRIPTION
**Pull request by jshlee**
gem-sw:CSC-Trigger-Upgrade-GEM-RPC-forSLHC12 does not compile without updates

### CODE REVIEW

**Comment by jshlee** [comment]
Hi Sven,

I'll merge this if there is no complaints from anyone.

Cheers,
Jason.

**Comment by dildick** [comment]
Does this new branch even compile in SLHC11?

**Comment by dildick** [comment]
By the way, that branch was already merged in official CMSSW on Friday, so it is available in the latest IB.

**Comment by jshlee** [comment]
Do you mean the whole CSC-Trigger-Upgrade-GEM-RPC-forSLHC12 branch was merged into the upcoming SLHC12?

**Comment by dildick** [comment]
https://github.com/cms-sw/cmssw/pull/3432. I'll send around an email with updates once SLHC12 is built.

**Comment by jshlee** [comment]
btw, with the merge this compiles

**Comment by dildick** [comment]
Ok.

**Pull request merged**
