### PR TITLE
official validation update

### PR DESCRIPTION
**Pull request by calabria**
I have collected all the changes needed in order to include GEMs into the official validation package. Some of those changes are not needed for the official release but only for our purposes (like the changes in the cfg files in Validation/RecoMuon concerning the eta range, binning, etc...). I have also added the RMS plots modifying some modules into DQMServises. They are useful for us but they increase the final number of histrograms and so we have to decide if they can go into the official release.

### CODE REVIEW

**Comment by dildick** [comment]
I propose you talk to Slava and then make a special topic branch starting from CMSSW_6_2_0_SLHC5 and re-apply the changes there.

**Comment by calabria** [comment]
Ok fine

**Comment by dildick** [comment]
@calabria is there any update on this?

**Comment by calabria** [comment]
not yet, if you prefer we can close this PR and I will make another PR when I am ready

**Comment by dildick** [comment]
Maybe yes. I guess we should start with a clean branch from official CMSSW and then merge both in cms-sw and gem-sw. That is what I will for further trigger dev.

**Comment by calabria** [comment]
I have updated some files introducing a boolean to switch on/off the use of GEM rechits. In particular GEMHitAssociator provides a vector of matched simHits that is empty when the boolean i set to false (default). MuonAssociator performs a loop over the tracking recHits, if there are no GEM recHits it does not crash, simply it goes on with the other rechits. A boolean is also introduced in MuonTrackValidator, if it is set to false, the eta distributions of the gem rechits is not filled. HitPattern performs a loop over the tracking rechits, so as the MABH, if it does not find gem rechits it goes on without crashing. The files modified in DQMServices add only the RMS plot so they don't represent a problem. I have removed all the other changes (mostly parameters in the cfi of Validation/RecoMuon) not needed in the official release. I have tested the code also when the GEMs are not included and it seems to work fine. In this PR I have added also an update for the analyzer I am currently using for the global reco validation.

**Pull request merged**
