### PR TITLE
Condor submitting files modified to fit the new version, AND:

### PR DESCRIPTION
**Pull request by giovanni-mocellin**
Production OK, however RESULTS ARE STRANGE!!!

### CODE REVIEW

**Comment by jshlee** [comment]
whats strange???

**Comment by jshlee** [comment]
rm Validation/GEMCosmicMuonStand/test/job.tar.gz

**Comment by giovanni-mocellin** [comment]
The efficiencies in the partitions are not distributed as expected. I see inefficiencies in central partitions and perfectly efficient edge partitions of top and bottom chambers... I will try to understand what is the possible cause.

**Comment by giovanni-mocellin** [comment]
I do not know why, but without the tar package, it was not working for me... That's why I was adding also that

**Comment by jshlee** [comment]
what does this tar do?

also, post the efficiencies here

**Comment by giovanni-mocellin** [comment]
The tar is the src folder compressed to be sent to condor jobs. Plots:

**Comment by giovanni-mocellin** [comment]
schermata 2018-06-21 alle 19 22 21

**Comment by jshlee** [comment]
rm tar.
if needed for condor, make the script make it

with the efficiency, what is different?

**Comment by giovanni-mocellin** [comment]
Ok for the tar.

Efficiency: the efficiency map looks weird: no efficiency drops in the expected regions (ieta = 1,8 of 5/X/T & 1/X/B) and some even large drops distributed here and there in the chambers...

**Comment by giovanni-mocellin** [comment]
I will discuss this with Jongseok today

**Pull request closed without merging**
