### PR TITLE
Variable relocating, add efficiency plot about local x,y

### PR DESCRIPTION
**Pull request by geonmo**
minPt, minEta and maxEta variables was moved for python configuration and 

Efficiency plots about digi local xy was added.

### CODE REVIEW

**Comment by dildick** [comment]
@jshlee -- could you look into this, please?

**Comment by jshlee** [comment]
what part did you want me to look at?

**Comment by dildick** [comment]
I'm wondering whether this needs to be included in gem-sw. (Maybe we already have it) If so, can you check the compilation, make sure it runs and remove excessive white spaces?

**Comment by geonmo** [comment]
Local XY plots were added.( +10 histogram )

**Pull request merged**
